package edu.plv.fes

import org.apache.shiro.SecurityUtils

/**
 * Generated by the Shiro plugin. This filters class protects all URLs
 * via access control by convention.
 */
class FESSecurityFilters {
    def filters = {
        all(uri: "/**") {
            before = {
                if (controllerName == 'assets' || SecurityUtils.subject.isAuthenticated() && controllerName == 'landingPage') return true

                // Access control by convention.
                accessControl()
            }
        }
    }
}
